<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Omne_Crud_Demo.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Omne-Crud-Demo.Abstractions\Omne-Crud-Demo.Abstractions.csproj" />
    <ProjectReference Include="..\Omne-Crud-Demo.Domain\Omne-Crud-Demo.Domain.csproj" />
  </ItemGroup>

</Project>
